/**
 * Generates src/environments/environment.ts and environment.development.ts
 * from process.env (CI/deploy) or a local .env file (dev).
 *
 * Required vars:
 *   SUPABASE_URL
 *   SUPABASE_KEY
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT, '.env');
const OUT_DIR = path.join(ROOT, 'src', 'environments');
const REQUIRED = ['SUPABASE_URL', 'SUPABASE_KEY'];

function loadDotEnv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const out = {};
  const content = fs.readFileSync(filePath, 'utf8');
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const fileVars = loadDotEnv(ENV_FILE);
const vars = {};
for (const key of REQUIRED) {
  vars[key] = process.env[key] || fileVars[key];
}

const missing = REQUIRED.filter((k) => !vars[k]);
if (missing.length) {
  console.error(
    `[set-env] Missing required env vars: ${missing.join(', ')}.\n` +
      `         Set them in your environment or in a .env file at the project root.\n` +
      `         See .env.example for the expected format.`
  );
  process.exit(1);
}

function buildFile(production) {
  return (
    `// AUTO-GENERATED by scripts/set-env.js — do not edit by hand.\n` +
    `export const environment = {\n` +
    `  production: ${production},\n` +
    `  supabaseUrl: '${vars.SUPABASE_URL}',\n` +
    `  supabaseKey: '${vars.SUPABASE_KEY}',\n` +
    `};\n`
  );
}

if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, 'environment.ts'), buildFile(true));
fs.writeFileSync(
  path.join(OUT_DIR, 'environment.development.ts'),
  buildFile(false)
);

console.log('[set-env] environment.ts and environment.development.ts generated.');
